name: WinxxLobby
version: '${project.version}'
main: net.winxxdeveloper.winxxlobby.Terminal
authors: [ LeticiaCHEAT ]
description: A lobby plugin with an exclusive Winxx Developer distribution.
commands:
  alerta:
  build:
  lobby:
    aliases: [spawn, hub]
  gm:
    aliases: [gamemode]
  gmc:
    aliases: [gm1, gmcreative, gmcriativo]
  gms:
    aliases: [gm0, gmsurvival]
  fly:
    aliases: [voar, asas]
  clearchat:
    aliases: [limparchat, chatclear]